#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -exuo pipefail

export DEBIAN_FRONTEND=noninteractive
export DBUS_SESSION_BUS_ADDRESS=/dev/null

sudo locale-gen en_US.UTF-8
sudo update-locale LANGUAGE=en_US.UTF-8
sudo update-locale LANG=en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8

apt-get update
apt-get -y install --no-install-recommends \
git python3 python3-dev python3-venv \
build-essential libffi-dev \
libtiff5-dev libjpeg8-dev zlib1g-dev \
libfreetype6-dev liblcms2-dev libwebp-dev \
curl libfontconfig libssl-dev \
libxml2-dev libxslt1-dev \
libxmlsec1-dev

NVM_DIR=”$HOME/.nvm”

# node & npm
if [ ! -d "$NVM_DIR" ]; then

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash

fi

[ -s “$NVM_DIR/nvm.sh” ] && \. “$NVM_DIR/nvm.sh”

[ -s "$NVM_DIR/bash_completion" ] && \.   "$NVM_DIR/bash_completion"

. ~/.profile
. ~/.bashrc

nvm ls && nvm install node && nvm install iojs && nvm install lts/* && nvm install lts/argon && nvm install lts/boron && nvm install lts/carbon && nvm install lts/dubnium && nvm install lts/erbium && nvm install 7.10.1 && nvm use 7.10.1 && nvm ls

npm install -g grunt-cli

node --version
npm --version
grunt --version
