#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -exuo pipefail

export DEBIAN_FRONTEND=noninteractive
export DBUS_SESSION_BUS_ADDRESS=/dev/null

SUPERDESK_DIR=/opt/superdesk/server
if [ ! -d "$SUPERDESK_DIR" ]; then
echo "   ****Superdesk installations is missing!**** " 1>&2 ; exit 1;
fi

SuperdeskDomain=${1:-'localhost'}

NewsRoomDomain=${2:-'localhost'}

_activate() {
    set +ux
    . /opt/newsroom/activate.sh
    set -ux
}

_missing_db() {
    curl -sI $ELASTICSEARCH_URL/$ELASTICSEARCH_INDEX | grep -q 404
}

_skip_install() {
    dpkg -l | grep '^ii.*'$1 && [ -z ${pkg_upgrade:-''} ]
}

## database
curl -o- https://raw.githubusercontent.com/BlackOrder/SuperdeskInstall/master/subScripts/database | bash


# elasticsearch
wait_elastic() {
    elastic=0
    while [ $elastic -eq 0 ]
    do
        curl -s "http://localhost:9200" 2>&1 > /dev/null \
            && elastic=1 \
            || echo "waiting for elastic..."
        sleep 5
    done
}

if ! _skip_install elasticsearch; then
    # for elasticsearch 2.4.x declare next
    # elastic_version=2.x
    version=${elastic_version:-1.7}
    curl -s https://packages.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://packages.elastic.co/elasticsearch/$version/debian stable main" \
        > /etc/apt/sources.list.d/elastic.list

    apt-get -y update
    apt-get -y install --no-install-recommends \
        openjdk-8-jre-headless \
        elasticsearch
    unset version
fi

# tune elasticsearch
cfg='/etc/elasticsearch/elasticsearch.yml'
[ -f "${cfg}.bak" ] || mv $cfg $cfg.bak
es_backups=/var/tmp/elasticsearch
if [ ! -d "$es_backups" ]; then
    mkdir $es_backups
    chown elasticsearch:elasticsearch $es_backups
fi
cat <<EOF > $cfg
network.bind_host: 0.0.0.0
node.local: true
discovery.zen.ping.multicast: false
path.repo: $es_backups
index.number_of_replicas: 0
EOF

systemctl enable elasticsearch
systemctl restart elasticsearch
wait_elastic

curl -s -XPUT 'http://localhost:9200/_snapshot/backups' \
    -d '{"type": "fs", "settings": {"location": "'$es_backups'"}}'
unset cfg es_backups


locale-gen en_US.UTF-8

[ -d /var/log/newsroom ] || mkdir -p /var/log/newsroom
systemctl disable rsyslog || true
systemctl stop rsyslog || true

cat <<"EOF" > /etc/logrotate.d/newsroom
/var/log/newsroom/*.log {
    rotate 7
    daily
    missingok
    copytruncate
    notifempty
    nocompress
    size 20M
}
EOF
logrotate /etc/logrotate.conf

f="/opt/newsroom/activate.sh"
dir=$(dirname "$f")
mkdir -p "$dir"

cat <<EOF > /opt/newsroom/activate.sh
. /opt/python3env/bin/activate

set -a
LC_ALL=en_US.UTF-8

# some settings required by client
PATH=/opt/newsroom/client/node_modules/.bin/:\$PATH
SUPERDESK_URL='http://$SuperdeskDomain/api'
SUPERDESK_WS_URL='ws://$SuperdeskDomain/ws'
set +a
EOF

_activate
pip install -U pip wheel

## prepare source code
repo=${repo:-'/opt/newsroom'}
[ -d $repo ] || mkdir $repo
cd $repo
if [ ! -d $repo/.git ]; then
    git init
    git remote add origin https://github.com/superdesk/newsroom.git
    repo_ref=${repo_ref:-'heads/master'}
    repo_sha=
    git fetch origin $repo_ref:
    git checkout ${repo_sha:-FETCH_HEAD}
    unset repo_sha
    unset repo repo_ref
fi

cd /opt/newsroom
time pip install -r requirements.txt

set +ux
source ~/.nvm/nvm.sh;
nvm use lts/*;
set -ux

time sudo npm install
time sudo npm run build


cat <<"EOF" > /opt/newsroom/activate.sh
. /opt/python3env/bin/activate

set -a
LC_ALL=en_US.UTF-8
PYTHONUNBUFFERED=1
PATH=node_modules/.bin/:$PATH

[ ! -f /opt/newsroom/env.sh ] || . /opt/newsroom/env.sh

NEWSROOM_SETTINGS=settings.py

CONTENTAPI_ELASTIC_INDEX=sd-master_ca
CONTENTAPI_ELASTICSEARCH_INDEX=sd-master_ca
CONTENTAPI_MONGO_URI=mongodb://data-sd/sd-master_ca
CONTENTAPI_URL=https://sd-master.test.superdesk.org/contentapi
ELASTICSEARCH_URL=http://data-sd:9200
set +a
EOF

_activate

cat <<EOF > /opt/newsroom/settings.py
import os

env = os.environ.get

DEBUG=False
WEBPACK_ASSETS_URL="http://$NewsRoomDomain/assets/"

MAIL_SERVER = env('MAIL_SERVER', '$NewsRoomDomain')
MAIL_PORT = int(env('MAIL_PORT', 25))
MAIL_USE_TLS = env('MAIL_USE_TLS', False)
MAIL_USE_SSL = env('MAIL_USE_SSL', False)
MAIL_USERNAME = env('MAIL_USERNAME', '')
MAIL_PASSWORD = env('MAIL_PASSWORD', '')
EOF

# Use latest honcho with --no-colour option
pip install -U honcho gunicorn

cat <<EOF > /opt/newsroom/Procfile
app: python app.py
logs: journalctl -u newsroom* -f >> /var/log/newsroom/main.log
EOF

cat <<"EOF" > /etc/systemd/system/newsroom.service
[Unit]
Description=newsroom
Wants=network.target
After=network.target

[Service]
ExecStart=/bin/sh -c '. /opt/newsroom/activate.sh && exec honcho start --no-colour'
WorkingDirectory=/opt/newsroom
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl enable newsroom
systemctl restart newsroom

# nginx
if ! _skip_install nginx; then
    curl -s http://nginx.org/keys/nginx_signing.key | apt-key add -
    echo "deb http://nginx.org/packages/ubuntu/ xenial nginx" \
        > /etc/apt/sources.list.d/nginx.list

    apt-get -y update
    apt-get -y install nginx
fi

path=/etc/nginx/conf.d
cat <<EOF > $path/newsroom.conf
server {
    listen 80;
    server_name $NewsRoomDomain;
    include $path/newsroom.inc;
}
EOF

cat <<EOF > $path/newsroom.inc
location / {
    proxy_pass http://localhost:5000;
    expires epoch;

    sub_filter_once off;
    sub_filter_types application/json;
    sub_filter 'http://localhost' 'http://\$host';
}

location /assets {
    alias /opt/newsroom/dist;
}
EOF

unset path
systemctl enable nginx
systemctl restart nginx


[ -z "${smtp-1}" ] || (
mails=/var/log/newsroom/mail
mkdir -p $mails

smtp_py=/var/tmp/smtp.py
cat <<EOF > $smtp_py
import argparse
import asyncore
import datetime as dt
import logging
import random
import smtpd
from email.parser import Parser
from pathlib import Path

log = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.DEBUG,
    datefmt='[%Y-%m-%d %H:%M:%S %Z]',
    format='%(asctime)s %(message)s'
)


class Server(smtpd.SMTPServer, object):
    """Logging-enabled SMTPServer instance."""

    def __init__(self, path, *args, **kwargs):
        super().__init__(*args, **kwargs)
        path = Path(path)
        path.mkdir(exist_ok=True)
        self._path = path

    def process_message(self, peer, mailfrom, rcpttos, data):
        msg = Parser().parsestr(data)
        subject = msg['subject']
        log.info('to=%r subject=%r', rcpttos, subject)
        for addr in rcpttos:
            name = (
                '{0:%Y%V/%w-%H%M%S}-{1:02d}-{2}.log'
                .format(dt.datetime.now(), random.randint(0, 99), addr)
            )
            log.info('filename=%r to=%r subject=%r', name, addr, subject)
            email = self._path / name
            email.parent.mkdir(exist_ok=True)
            email.write_text(data)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Run an SMTP server.')
    parser.add_argument('addr', help='addr to bind to')
    parser.add_argument('port', type=int, help='port to bind to')
    parser.add_argument('path', help='directory to store to')
    args = parser.parse_args()

    log.info('Starting SMTP server at {0}:{1}'.format(args.addr, args.port))
    server = Server(args.path, (args.addr, args.port), None)
    try:
        asyncore.loop()
    except KeyboardInterrupt:
        log.info('Cleaning up')
EOF

cat <<EOF >> /etc/nginx/conf.d/newsroom.inc
location /mail {
    alias $mails/;
    default_type text/plain;
    autoindex on;
    autoindex_exact_size off;
}
EOF

service=newsroom-smtp
cat <<EOF > /etc/systemd/system/$service.service
[Unit]
Description=Dev SMTP server for newsroom, it doesn't send real emails
Wants=network.target
After=network.target

[Service]
ExecStart=/bin/sh -c '. /opt/python3env/bin/activate && exec python3 $smtp_py $NewsRoomDomain 25 $mails'
WorkingDirectory=/opt/newsroom
Restart=always

[Install]
WantedBy=multi-user.target
EOF
systemctl enable $service
systemctl restart $service

nginx -s reload
unset smtp_py mails
)
